/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.asiakastilaus;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Kone1
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI(String tunnus) {
        initComponents();
        //asetetaan avautumaan keskelle näyttöö
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuTiedosto = new javax.swing.JMenu();
        jmnuLopeta = new javax.swing.JMenuItem();
        jmnuHallinta = new javax.swing.JMenu();
        jmnuAsiakasrekisteri = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmnuTiedosto.setText("Tiedosto");

        jmnuLopeta.setText("Lopeta");
        jmnuLopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuLopetaActionPerformed(evt);
            }
        });
        jmnuTiedosto.add(jmnuLopeta);

        jMenuBar1.add(jmnuTiedosto);

        jmnuHallinta.setText("Hallinta");

        jmnuAsiakasrekisteri.setText("Asiakasrekisteri");
        jmnuAsiakasrekisteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuAsiakasrekisteriActionPerformed(evt);
            }
        });
        jmnuHallinta.add(jmnuAsiakasrekisteri);

        jMenuBar1.add(jmnuHallinta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnuAsiakasrekisteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuAsiakasrekisteriActionPerformed
        // Avaa asiakasrekisterihallinta ikkunan
        Asiakasrekisterihallinta as = new Asiakasrekisterihallinta();
        as.setVisible(true);
    }//GEN-LAST:event_jmnuAsiakasrekisteriActionPerformed

    private void jmnuLopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuLopetaActionPerformed
        //käytetään lopetus metodia
        lopetus();
    }//GEN-LAST:event_jmnuLopetaActionPerformed
    void lopetus() {
        // muutetaan vastaus vaihtoehdot kyllä ja ei
        UIManager.put("OptionPane.yesButtonText","Kyllä");
        UIManager.put("OptionPane.noButtonText","Ei");
        // varmistetaan JOptionPane-ikkunalla halutaanko varmasti suorittaa valittu    
        int kysy = JOptionPane.showConfirmDialog(null, "Haluatko lopettaa" , "Lopetus", JOptionPane.YES_NO_OPTION);
        if (kysy == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            return;
        }
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmnuAsiakasrekisteri;
    private javax.swing.JMenu jmnuHallinta;
    private javax.swing.JMenuItem jmnuLopeta;
    private javax.swing.JMenu jmnuTiedosto;
    // End of variables declaration//GEN-END:variables
}
