/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.asiakastilaus;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kone1
 */
public class Kirjautuminen extends javax.swing.JFrame {

    /**
     * Creates new form Kirjautuminen
     */
    public Kirjautuminen() {
        initComponents();
        //asetetaan avautumaan keskelle näyttöö
        this.setLocationRelativeTo(null);
    }

    public Connection luoYhteys() {
        Connection cn = null;
        // Muuta oman Amazon palvelimesi osoite, tietokannan nimi sekä käyttäjätunnus ja salasana, jolla yhteys muodostetaan
        try {
            cn = DriverManager.
                    getConnection("jdbc:mysql://" + "ec2-16-170-133-46.eu-north-1.compute.amazonaws.com" + ":3306/ASIAKASTILAUS", "kehittaja", "Koira123!");
            return cn;
        } catch (SQLException e) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage());
            e.printStackTrace();
            return null;
        }
    }
    public void sulje() {
        
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnKirjaudu = new javax.swing.JButton();
        chkSalasana = new javax.swing.JCheckBox();
        jbtnTesti = new javax.swing.JButton();
        jpswSalasana = new javax.swing.JPasswordField();
        jtxtTunnus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSQL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tunnus:");

        jLabel2.setText("Salasana:");

        jbtnKirjaudu.setText("Kirjaudu");
        jbtnKirjaudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKirjauduActionPerformed(evt);
            }
        });

        chkSalasana.setText("Näytä Salasana");
        chkSalasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSalasanaActionPerformed(evt);
            }
        });

        jbtnTesti.setText("Testi");
        jbtnTesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestiActionPerformed(evt);
            }
        });

        jLabel3.setText("Tervetuloa Asiakastilaus-tietojärjestelmään");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jpswSalasana)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnTesti)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnKirjaudu)
                                .addGap(35, 35, 35)
                                .addComponent(chkSalasana))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jtxtSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpswSalasana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnKirjaudu)
                    .addComponent(chkSalasana))
                .addGap(18, 18, 18)
                .addComponent(jbtnTesti)
                .addGap(33, 33, 33)
                .addComponent(jtxtSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestiActionPerformed
        // TODO add your handling code here:
        // Tietokantayhteyden testaus-painike
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Missä on MariaDB JDBC ajuri? Oletko ladannut mariadb connectorinosoitteesta: https://mariadb.com/downloads/#connectors ja lisännyt sen Netbeansissä AsiakasrekisteriLibraries-Add JAR/Folder kohdassa? ");
            e.printStackTrace();
            return;
        }
        System.out.println("MySQL JDBC Driver rekisteröity!");
        Connection connection = null;
        // Muokkaa palvelimen osoite, tietokannan nimi ja läyttäjätunnus sekä salasana vastaamaan omaaympäristöäsi
        try {
            connection = DriverManager.
                    getConnection("jdbc:mysql://" + "ec2-16-170-133-46.eu-north-1.compute.amazonaws.com" + ":3306/ASIAKASTILAUS", "kehittaja", "Koira123!");
        } catch (SQLException e) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage());
        }
        if (connection != null) {
            System.out.println("Hienoa ja onnittelut! Sait luotua yhteyden tietokantaasi. Voit aloittaakäyttöliittymän koodaamisen!");
        } else {
            System.out.println("Pahus, tarkista vielä, että kaikki tarvittava on tehty ja virheitä ei ole!");
        }

    }//GEN-LAST:event_jbtnTestiActionPerformed

    private void jbtnKirjauduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKirjauduActionPerformed
        // Käyttöliittymästä haettu tunnus ja salasana
        String tunnus = jtxtTunnus.getText();
        String oikeasalasanatietokannassa = "";
        //Miksi salasanat char eikä String - turvallisuus
        char annettusalasana[] = jpswSalasana.getPassword();
        char [] oikeasalasanataulukkona=null;
        //muodostetaan tietokantayhteys
        Connection cn = luoYhteys();
        //kahdessa seuraavassa rivissä heikkouksia mitä ja missä?
        String sqlKysely = "SELECT TUNNUS, DES_DECRYPT(SALASANA,'salainenavain') AS SALASANA FROM KAYTTAJA WHERE TUNNUS='"+tunnus+"'";
        jtxtSQL.setText(sqlKysely);
        try {
            PreparedStatement stm = cn.prepareStatement(sqlKysely);
            ResultSet tulos = stm.executeQuery();
            //jos tulos.next, tunnus annettu oikein
            if(tulos.next()) {
                // Selvitetään ja haetaan resultset-objektista salasana ja trimmataan lopuksi
                oikeasalasanatietokannassa = tulos.getString("SALASANA").trim();
                // muunnetaan string muotoinen salasana taulukoksi
                oikeasalasanataulukkona = oikeasalasanatietokannassa.toCharArray();
                // jos tallennettu salasana ja annettu salasana täsmää...
                if(Arrays.equals(annettusalasana, oikeasalasanataulukkona)) {
                    //Välitetään käyttäjätunnus GUI-luokan muodostimelle ja tuodaan lomake esille
                    GUI g = new GUI(tunnus);
                    g.setVisible(true);
                    // suljetaan kirjautumislomake
                    sulje();
                } else {
                    // miksi ei pidä kertoa kumpi ollut väärin tunnus vai salasana?
                    JOptionPane.showMessageDialog(this,"Tunnus tai salasana on väärin. Yritä uudelleen");
                    jtxtTunnus.requestFocus();
                    return;
                }
            }
        } catch (SQLException ex) { 
            Logger.getLogger(Kirjautuminen.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Tyhjennetään tietoturvasyistä salasanojen käyttöön liittyvät muuttujat täyttämällä taulukkonollamerkeillä ja ""
        Arrays.fill(oikeasalasanataulukkona, '0');
        oikeasalasanatietokannassa="";
    }//GEN-LAST:event_jbtnKirjauduActionPerformed

    private void chkSalasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSalasanaActionPerformed
        // TODO add your handling code here:
        if (chkSalasana.isSelected()) {
            jpswSalasana.setEchoChar((char)0);
            chkSalasana.setSelected(true);
        } else {
            jpswSalasana.setEchoChar('+');
            chkSalasana.setSelected(false);
        }
    }//GEN-LAST:event_chkSalasanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kirjautuminen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSalasana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnKirjaudu;
    private javax.swing.JButton jbtnTesti;
    private javax.swing.JPasswordField jpswSalasana;
    private javax.swing.JTextField jtxtSQL;
    private javax.swing.JTextField jtxtTunnus;
    // End of variables declaration//GEN-END:variables
}
